export enum LinksEnum {
    home = "/",
    login = "/login",
    forgotten_password = "/password-forgot",
    change_password = "/password-change",
    not_found = "/not-found",
    server_error = "/server-error",

    organisation = "/organisations",
    users = "/users",
    users_settings = "/user-settings",
    categories = "/categories",
    account_informations = "/account-informations",
    password_settings = "/password-settings",
    notifications = "/notifications",
    partners = "/partners",
    sellers = "/sellers",
    orders = "/orders",
    products = "/products",
    product_cancelling = "/product-cancelling",
    returns = "/returns",
    icons = "/icons",
    blogs = "/blogs",
    brands = "/brands",
    banners = "/banners",
    colors = "/colors",
    clients_refunds = "/clients-refunds",
    sellers_accounting = "/sellers-accounting",
    statistics = "/statistics"
}
